Feature/updatepackagemanagement
AdamsLair/duality-docs pull request #51
Opened 2020-05-19 13:30 UTC by Barsonax

2020-05-19 18:02 UTC, SirePi requested changes

2020-05-19 18:02 UTC, SirePi commented on pages/v4/Package-Management.md
> +  - A full list of metadata properties van be found [here](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#nuget-metadata-properties)
Typo:  "...properties *can* be found..."

2020-05-19 18:03 UTC, SirePi commented on pages/v4/Package-Management.md
> +  - A full list of metadata properties van be found [here](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#nuget-metadata-properties)
Line 56

2020-05-19 18:54 UTC, Barsonax commented
As expected some allocations are happening. Seems to be about 144 bytes per call which does impact performance quite a bit.

```
// * Summary *

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18363.836 (1909/November2018Update/19H2)
AMD Ryzen 9 3900X, 1 CPU, 24 logical and 12 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4180.0), X64 RyuJIT
  DefaultJob : .NET Framework 4.8 (4.8.4180.0), X64 RyuJIT


|                Method |      N |             Mean |          Error |         StdDev |     Gen 0 |     Gen 1 |    Gen 2 |  Allocated |
|---------------------- |------- |-----------------:|---------------:|---------------:|----------:|----------:|---------:|-----------:|
| CallEndlessSubRoutine |      1 |         72.61 ns |       0.835 ns |       0.781 ns |    0.0869 |         - |        - |      144 B |
| CallEndlessSubRoutine |     10 |        672.92 ns |       3.946 ns |       3.498 ns |    0.8698 |         - |        - |     1444 B |
| CallEndlessSubRoutine |    100 |      6,785.61 ns |      32.611 ns |      27.232 ns |    8.6975 |         - |        - |    14443 B |
| CallEndlessSubRoutine |   1000 |     78,150.10 ns |     691.155 ns |     646.507 ns |   56.3965 |   14.0381 |        - |   144427 B |
| CallEndlessSubRoutine |  10000 |  1,027,735.81 ns |  11,053.970 ns |  10,339.890 ns |  230.4688 |  115.2344 |        - |  1444252 B |
| CallEndlessSubRoutine | 100000 | 29,019,037.50 ns | 248,125.998 ns | 232,097.212 ns | 2625.0000 | 1093.7500 | 343.7500 | 14442578 B |
```

2020-05-20 11:03 UTC, SirePi approved these changes

2020-05-20 12:06 UTC, merged